"""Generated markdown ledgers: the canon-shaped views of state.json.

The JSON state is the single source of truth; these files are compiled
views regenerated at every gate and committed with it. No LLM ever writes
them, so the bookkeeping-drift class of findings (stale work logs,
misattributed rounds, missing seal evidence fields) is structurally
impossible: the ledger cannot disagree with the ledger's source.

Deterministic by construction: content derives only from state (no
generation-time clock)."""

import os

from . import state as st

LEDGER_DIR = "docs"
MILESTONE_FILE = os.path.join(LEDGER_DIR, "MILESTONE.md")
REVIEW_LOG_FILE = os.path.join(LEDGER_DIR, "review-log.md")
CLOSURES_DIR = os.path.join(LEDGER_DIR, "closures")

_GENERATED = (
    "<!-- GENERATED by the orchestrator from .orchestrator/state.json — do "
    "not edit; edits are overwritten at the next gate. -->\n\n"
)


def _slice_title(state, slice_id):
    for sl in state["milestone"]["slices"]:
        if sl["id"] == slice_id:
            return sl["title"]
    return "?"


def _unit_label(state, unit):
    if unit["kind"] == "skeleton":
        return "skeleton"
    return "%s-%02d (%s)" % (
        unit["kind"], unit["slice_id"], _slice_title(state, unit["slice_id"])
    )


def _dispositions(result):
    counts = {}
    for f in result.get("findings", []):
        d = f.get("disposition") or "reported"
        counts[d] = counts.get(d, 0) + 1
    return counts


def _fmt_dispositions(counts):
    if not counts:
        return "clean"
    return ", ".join("%d %s" % (counts[k], k) for k in sorted(counts))


def render_milestone(state):
    m = state["milestone"]
    lines = [
        _GENERATED + "# Milestone",
        "",
        "Status: **%s**" % m["status"],
        "",
        "## Goal",
        "",
        state["goal"],
        "",
        "## Slices",
        "",
        "| Slice | Title |",
        "|---|---|",
    ]
    for sl in m["slices"]:
        lines.append("| %02d | %s |" % (sl["id"], sl["title"]))
    lines += [
        "",
        "## Units",
        "",
        "| Unit | Status | Rounds | Seal attempts | Gate commit |",
        "|---|---|---|---|---|",
    ]
    for unit in state["units"]:
        seals = ", ".join(
            "a%d:%s"
            % (
                s["attempt"],
                "pass" if s["passed"] else ("invalid" if s["invalidated"] else "findings"),
            )
            for s in unit["seals"]
        ) or "-"
        lines.append(
            "| %s | %s | %d | %s | %s |"
            % (
                _unit_label(state, unit),
                unit["status"],
                len(unit["rounds"]),
                seals,
                unit.get("gate_commit") or "-",
            )
        )
    failure = state.get("failure")
    if failure:
        lines += [
            "",
            "## Failure",
            "",
            "- at: %s" % failure.get("at"),
            "- unit: %s" % failure.get("unit"),
            "- reason: %s" % failure.get("reason"),
        ]
    return "\n".join(lines) + "\n"


def render_review_log(state):
    lines = [_GENERATED + "# Review Log", ""]
    for unit in state["units"]:
        lines += ["## %s" % _unit_label(state, unit), ""]
        if unit.get("draft"):
            lines += [
                "- draft: kind `%s`, artifact `%s` (raw: `%s`)"
                % (
                    unit["draft"].get("kind"),
                    unit.get("artifact") or "-",
                    unit["draft"].get("raw_path"),
                ),
            ]
        if unit["rounds"]:
            lines += [
                "",
                "| Round | Kind | Family | Findings | Triage | Raw |",
                "|---|---|---|---|---|---|",
            ]
            for r in unit["rounds"]:
                result = r["result"]
                consultations = sum(
                    1 for f in result.get("findings", []) if f.get("consultation")
                )
                triage = _fmt_dispositions(_dispositions(result))
                if consultations:
                    triage += " (%d consulted)" % consultations
                if r.get("invalidated"):
                    triage = "INVALIDATED: %s" % r["invalidated"]
                lines.append(
                    "| %s | %s | %s | %d | %s | `%s` |"
                    % (
                        r["id"],
                        r["kind"],
                        r["family"],
                        len(result.get("findings", [])),
                        triage,
                        r.get("raw_path"),
                    )
                )
        for seal in unit["seals"]:
            lines += [
                "",
                "### Seal attempt a%d — %s"
                % (
                    seal["attempt"],
                    "PASSED"
                    if seal["passed"]
                    else ("INVALIDATED" if seal["invalidated"] else "findings"),
                ),
                "",
            ]
            if seal["invalidated"]:
                lines.append("- invalidated: %s" % seal["invalidated"])
            for fam in sorted(seal["halves"]):
                half = seal["halves"][fam]
                result = half.get("result") or {}
                lines.append(
                    "- %s half: %d finding(s); workspace_modified=%s; raw `%s`"
                    % (
                        fam,
                        len(result.get("findings", [])),
                        half.get("workspace_modified"),
                        half.get("raw_path"),
                    )
                )
                for f in result.get("findings", []):
                    lines.append(
                        "  - [%s] %s" % (f.get("severity"), f.get("summary"))
                    )
        lines.append("")
    return "\n".join(lines) + "\n"


def render_adjudications(state):
    entries = st.adjudicated_rejections(state)
    lines = [_GENERATED + "# Adjudicated Rejections", ""]
    if not entries:
        lines.append("(none)")
        return "\n".join(lines) + "\n"
    lines += [
        "Settled findings: re-raising one requires referencing its id with",
        "genuinely new evidence (`contests`).",
        "",
    ]
    for e in entries:
        lines.append("## [%s]" % e["id"])
        lines.append("")
        lines.append("- unit: %s" % e.get("unit"))
        lines.append("- severity: %s" % e.get("severity"))
        lines.append("- finding: %s" % e.get("summary"))
        lines.append("- rationale: %s" % (e.get("rationale") or "(none)"))
        if e.get("prevention"):
            lines.append(
                "- prevention: %s (%s)"
                % (
                    e["prevention"].get("documented_in"),
                    e["prevention"].get("note"),
                )
            )
        lines.append("")
    return "\n".join(lines) + "\n"


def render_closure(state, unit):
    closed = unit.get("closed_record") or {}
    return (
        _GENERATED
        + "# Closure — slice %02d (%s)\n\n" % (unit["slice_id"], _slice_title(state, unit["slice_id"]))
        + "- closed at: %s\n" % closed.get("at")
        + "- rounds: %s\n" % closed.get("rounds")
        + "- seal attempts: %s\n" % closed.get("seal_attempts")
        + "- gate commit: %s\n" % (unit.get("gate_commit") or "(this commit)")
        + "- review state: review_clean (double seal passed on an unchanged "
        "workspace)\n"
    )


def generate(state, workspace):
    """Write all ledger views. Returns the list of workspace-relative paths."""
    written = []
    docs = os.path.join(workspace, LEDGER_DIR)
    os.makedirs(docs, exist_ok=True)
    for rel, content in (
        (MILESTONE_FILE, render_milestone(state)),
        (REVIEW_LOG_FILE, render_review_log(state)),
        (os.path.join(LEDGER_DIR, "adjudications.md"), render_adjudications(state)),
    ):
        path = os.path.join(workspace, rel)
        with open(path, "w", encoding="utf-8") as fh:
            fh.write(content)
        written.append(rel)
    for unit in state["units"]:
        if unit["kind"] == "slice_impl" and unit.get("closed_record"):
            rel = os.path.join(CLOSURES_DIR, "slice-%02d.md" % unit["slice_id"])
            os.makedirs(os.path.join(workspace, CLOSURES_DIR), exist_ok=True)
            with open(os.path.join(workspace, rel), "w", encoding="utf-8") as fh:
                fh.write(render_closure(state, unit))
            written.append(rel)
    return written
