"""Generated markdown ledgers: the canon-shaped views of state.json.

The JSON state is the single source of truth; these files are compiled
views regenerated at every gate and committed with it. No LLM ever writes
them, so the bookkeeping-drift class of findings (stale work logs,
misattributed rounds, missing seal evidence fields) is structurally
impossible: the ledger cannot disagree with the ledger's source.

Deterministic by construction: content derives only from state (no
generation-time clock)."""

import os
import re

from . import state as st

# Legacy flat layout (runs created before docs_dir existed): everything
# under docs/ with the record named MILESTONE.md. Canonical layout (any
# other docs_dir, default implementation/milestones/<slug>): the record is
# README.md, slice notes live under slices/, and the parent directory
# carries a machine-maintained milestone index.
LEGACY_DIR = "docs"


def docs_dir(state):
    return (state.get("docs_dir") or LEGACY_DIR).strip("/") or LEGACY_DIR


def is_legacy(state):
    return docs_dir(state) == LEGACY_DIR


def record_path(state):
    return os.path.join(
        docs_dir(state), "MILESTONE.md" if is_legacy(state) else "README.md"
    )


def review_log_path(state):
    return os.path.join(docs_dir(state), "review-log.md")


def adjudications_path(state):
    return os.path.join(docs_dir(state), "adjudications.md")


def closures_dir(state):
    return os.path.join(docs_dir(state), "closures")


def skeleton_path(state):
    return os.path.join(docs_dir(state), "skeleton.md")


def slice_note_path(state, slice_id):
    if is_legacy(state):
        return os.path.join(docs_dir(state), "slice-%02d.md" % slice_id)
    return os.path.join(docs_dir(state), "slices", "slice-%02d.md" % slice_id)


def index_path(state):
    """The parent directory's milestone index (canonical layout only —
    the legacy layout has no meaningful parent to write into)."""
    if is_legacy(state):
        return None
    parent = os.path.dirname(docs_dir(state))
    if not parent:
        return None
    return os.path.join(parent, "README.md")

_GENERATED = (
    "<!-- GENERATED by the orchestrator from .orchestrator/state.json — do "
    "not edit; edits are overwritten at the next gate. -->\n\n"
)


def _slice_title(state, slice_id):
    for sl in state["milestone"]["slices"]:
        if sl["id"] == slice_id:
            return sl["title"]
    return "?"


def _unit_label(state, unit):
    if unit["kind"] == "skeleton":
        return "skeleton"
    return "%s-%02d (%s)" % (
        unit["kind"], unit["slice_id"], _slice_title(state, unit["slice_id"])
    )


def _dispositions(result):
    counts = {}
    for f in result.get("findings", []):
        d = f.get("disposition") or "reported"
        counts[d] = counts.get(d, 0) + 1
    return counts


def _fmt_dispositions(counts):
    if not counts:
        return "clean"
    return ", ".join("%d %s" % (counts[k], k) for k in sorted(counts))


def render_milestone(state):
    m = state["milestone"]
    lines = [
        _GENERATED + "# Milestone",
        "",
        "Status: **%s**" % m["status"],
        "",
        "## Goal",
        "",
        state["goal"],
        "",
        "## Slices",
        "",
        "| Slice | Title |",
        "|---|---|",
    ]
    for sl in m["slices"]:
        lines.append("| %02d | %s |" % (sl["id"], sl["title"]))
    lines += [
        "",
        "## Units",
        "",
        "| Unit | Status | Rounds | Seal attempts | Gate commit |",
        "|---|---|---|---|---|",
    ]
    for unit in state["units"]:
        seals = ", ".join(
            "a%d:%s"
            % (
                s["attempt"],
                "pass" if s["passed"] else ("invalid" if s["invalidated"] else "findings"),
            )
            for s in unit["seals"]
        ) or "-"
        lines.append(
            "| %s | %s | %d | %s | %s |"
            % (
                _unit_label(state, unit),
                unit["status"],
                len(unit["rounds"]),
                seals,
                unit.get("gate_commit") or "-",
            )
        )
    failure = state.get("failure")
    if failure:
        lines += [
            "",
            "## Failure",
            "",
            "- at: %s" % failure.get("at"),
            "- unit: %s" % failure.get("unit"),
            "- reason: %s" % failure.get("reason"),
        ]
    return "\n".join(lines) + "\n"


def render_review_log(state):
    lines = [_GENERATED + "# Review Log", ""]
    for unit in state["units"]:
        lines += ["## %s" % _unit_label(state, unit), ""]
        if unit.get("draft"):
            lines += [
                "- draft: kind `%s`, artifact `%s` (raw: `%s`)"
                % (
                    unit["draft"].get("kind"),
                    unit.get("artifact") or "-",
                    unit["draft"].get("raw_path"),
                ),
            ]
        if unit["rounds"]:
            lines += [
                "",
                "| Round | Kind | Family | Findings | Triage | Raw |",
                "|---|---|---|---|---|---|",
            ]
            for r in unit["rounds"]:
                result = r["result"]
                consultations = sum(
                    1 for f in result.get("findings", []) if f.get("consultation")
                )
                triage = _fmt_dispositions(_dispositions(result))
                if consultations:
                    triage += " (%d consulted)" % consultations
                if r.get("invalidated"):
                    triage = "INVALIDATED: %s" % r["invalidated"]
                lines.append(
                    "| %s | %s | %s | %d | %s | `%s` |"
                    % (
                        r["id"],
                        r["kind"],
                        r["family"],
                        len(result.get("findings", [])),
                        triage,
                        r.get("raw_path"),
                    )
                )
        for seal in unit["seals"]:
            lines += [
                "",
                "### Seal attempt a%d — %s"
                % (
                    seal["attempt"],
                    "PASSED"
                    if seal["passed"]
                    else ("INVALIDATED" if seal["invalidated"] else "findings"),
                ),
                "",
            ]
            if seal["invalidated"]:
                lines.append("- invalidated: %s" % seal["invalidated"])
            for fam in sorted(seal["halves"]):
                half = seal["halves"][fam]
                result = half.get("result") or {}
                lines.append(
                    "- %s half: %d finding(s); workspace_modified=%s; raw `%s`"
                    % (
                        fam,
                        len(result.get("findings", [])),
                        half.get("workspace_modified"),
                        half.get("raw_path"),
                    )
                )
                for f in result.get("findings", []):
                    lines.append(
                        "  - [%s] %s" % (f.get("severity"), f.get("summary"))
                    )
        lines.append("")
    return "\n".join(lines) + "\n"


def render_adjudications(state):
    entries = st.adjudicated_rejections(state)
    lines = [_GENERATED + "# Adjudicated Rejections", ""]
    if not entries:
        lines.append("(none)")
        return "\n".join(lines) + "\n"
    lines += [
        "Settled findings: re-raising one requires referencing its id with",
        "genuinely new evidence (`contests`).",
        "",
    ]
    for e in entries:
        lines.append("## [%s]" % e["id"])
        lines.append("")
        lines.append("- unit: %s" % e.get("unit"))
        lines.append("- severity: %s" % e.get("severity"))
        lines.append("- finding: %s" % e.get("summary"))
        lines.append("- rationale: %s" % (e.get("rationale") or "(none)"))
        if e.get("prevention"):
            lines.append(
                "- prevention: %s (%s)"
                % (
                    e["prevention"].get("documented_in"),
                    e["prevention"].get("note"),
                )
            )
        lines.append("")
    return "\n".join(lines) + "\n"


def render_closure(state, unit):
    closed = unit.get("closed_record") or {}
    return (
        _GENERATED
        + "# Closure — slice %02d (%s)\n\n" % (unit["slice_id"], _slice_title(state, unit["slice_id"]))
        + "- closed at: %s\n" % closed.get("at")
        + "- rounds: %s\n" % closed.get("rounds")
        + "- seal attempts: %s\n" % closed.get("seal_attempts")
        + "- gate commit: %s\n" % (unit.get("gate_commit") or "(this commit)")
        + "- review state: review_clean (double seal passed on an unchanged "
        "workspace)\n"
    )


INDEX_START = "<!-- impl_roadmap:milestones:start -->"
INDEX_END = "<!-- impl_roadmap:milestones:end -->"


class LedgerError(RuntimeError):
    """A ledger cannot be written safely (hostile/malformed index file).
    The driver records this as a run failure instead of crashing with
    the sealed transition unsaved."""


def _sanitize_label(label):
    """Row labels are display text inside a markdown table cell and a
    link: pipes/newlines/brackets would corrupt the table or the link."""
    out = str(label)
    for bad, repl in (("|", "-"), ("[", "("), ("]", ")"), ("\n", " "),
                      ("\r", " ")):
        out = out.replace(bad, repl)
    return " ".join(out.split()) or "milestone"


def _row_target(row):
    """The link-target directory of an index row — the milestone's stable
    identity (labels are display text and may collide)."""
    m = re.search(r"\]\(([^)]+)/\)", row)
    return m.group(1) if m else None


def _index_row(state):
    m = state["milestone"]
    label = _sanitize_label(
        state.get("name") or os.path.basename(docs_dir(state))
    )
    closed = "-"
    if m["status"] == "closed":
        for e in reversed(state["events"]):
            if e.get("at"):
                closed = e["at"][:10]
                break
    return "| [%s](%s/) | %s | %d | %s | %s |" % (
        label,
        os.path.basename(docs_dir(state)),
        m["status"],
        len(m["slices"]),
        (state.get("created_at") or "")[:10],
        closed,
    )


def render_index_update(state, existing_text):
    """Upsert this milestone's row into the parent index. Hand-written
    content outside the marker block is preserved byte-for-byte; the
    block itself is machine territory. Rows are keyed on the milestone
    link cell."""
    row = _index_row(state)
    key = _row_target(row)
    header = (
        "| Milestone | Status | Slices | Opened | Closed |\n"
        "|---|---|---|---|---|"
    )
    if existing_text and (
        INDEX_START in existing_text or INDEX_END in existing_text
    ):
        # Machine block present: it must be exactly one well-ordered
        # START/END pair, or rewriting could silently eat hand-written
        # prose. Anything else is operator territory: fail loudly.
        if (
            existing_text.count(INDEX_START) != 1
            or existing_text.count(INDEX_END) != 1
            or existing_text.index(INDEX_END)
            < existing_text.index(INDEX_START)
        ):
            raise LedgerError(
                "milestone index has malformed impl_roadmap markers; fix "
                "the file by hand (exactly one start marker followed by "
                "one end marker)"
            )
        before, rest = existing_text.split(INDEX_START, 1)
        block, after = rest.split(INDEX_END, 1)
        rows = [
            ln
            for ln in block.strip().splitlines()
            if ln.startswith("|") and not ln.startswith("|---")
            and not ln.startswith("| Milestone")
        ]
        rows = [r for r in rows if _row_target(r) != key]
        rows.append(row)
        block_text = "\n%s\n%s\n" % (header, "\n".join(rows))
        return before + INDEX_START + block_text + INDEX_END + after
    base = existing_text or "# Milestone Index\n\n"
    if not base.endswith("\n"):
        base += "\n"
    return (
        base
        + "\n"
        + INDEX_START
        + "\n%s\n%s\n" % (header, row)
        + INDEX_END
        + "\n"
    )


def generate(state, workspace):
    """Write all ledger views. Returns the list of workspace-relative paths."""
    written = []
    docs = os.path.join(workspace, docs_dir(state))
    os.makedirs(docs, exist_ok=True)
    for rel, content in (
        (record_path(state), render_milestone(state)),
        (review_log_path(state), render_review_log(state)),
        (adjudications_path(state), render_adjudications(state)),
    ):
        path = os.path.join(workspace, rel)
        with open(path, "w", encoding="utf-8") as fh:
            fh.write(content)
        written.append(rel)
    for unit in state["units"]:
        if unit["kind"] == "slice_impl" and unit.get("closed_record"):
            rel = os.path.join(
                closures_dir(state), "slice-%02d.md" % unit["slice_id"]
            )
            os.makedirs(
                os.path.join(workspace, closures_dir(state)), exist_ok=True
            )
            with open(os.path.join(workspace, rel), "w", encoding="utf-8") as fh:
                fh.write(render_closure(state, unit))
            written.append(rel)
    idx = index_path(state)
    if idx:
        idx_abs = os.path.join(workspace, idx)
        existing = None
        if os.path.exists(idx_abs):
            try:
                with open(idx_abs, "r", encoding="utf-8") as fh:
                    existing = fh.read()
            except UnicodeDecodeError:
                raise LedgerError(
                    "milestone index %s is not valid UTF-8; a lossy "
                    "rewrite would mangle hand-written content — fix the "
                    "file's encoding by hand" % idx
                )
        with open(idx_abs, "w", encoding="utf-8") as fh:
            fh.write(render_index_update(state, existing))
        written.append(idx)
    return written
