"""Unit tests for the generated markdown ledgers (orchestrator/ledgers.py).

The ledgers are compiled views of state.json: deterministic pure functions
of the state dict (no generation-time clock), stamped with a GENERATED
marker, written under docs/ by generate(). These tests drive them with
small handcrafted states covering the interesting shapes under the
review/fix separation model: a reported review finding, a fix_findings
round (fixed / rejected-with-consultation), a clean delta review, an
INVALIDATED seal attempt, a findings seal attempt, a passed seal attempt,
a closed slice_impl, a failed run, and the adjudications ledger derived
from the rejected findings.
"""

import copy
import os
import tempfile
import unittest

from orchestrator import ledgers
from orchestrator import state as st

GENERATED_MARKER = "<!-- GENERATED by the orchestrator"

ADJ_ID = "skeleton-claude-r1/F1"
ADJ_RATIONALE = (
    "opposite family agreed the goal was already float-typed by the CLI "
    "contract; wording clarified for readability only"
)


def _clean_half(raw_path):
    return {
        "result": {"findings": []},
        "raw_path": raw_path,
        "duration_s": 1.0,
        "workspace_modified": False,
    }


def make_state():
    """A small but structurally complete state under the review/fix model:
    a sealed skeleton (reported finding -> fixer fixed -> clean delta ->
    reported finding -> fixer REJECTED with consultation+prevention -> clean
    round -> passed seal), a bare sealed slice_doc, and a closed slice_impl
    (verification fix episode + clean claude round) whose seal history is
    a1 INVALIDATED -> a2 findings -> a3 passed."""
    return {
        "goal": "Ship a tiny calculator with tests",
        "milestone": {
            "status": "closed",
            "slices": [{"id": 1, "title": "Calculator core"}],
        },
        "failure": None,
        "units": [
            {
                "kind": "skeleton",
                "slice_id": None,
                "status": "sealed",
                "artifact": "docs/skeleton.md",
                "draft": {
                    "kind": "draft_skeleton",
                    "raw_path": ".orchestrator/raw/skeleton-draft.txt",
                },
                "rounds": [
                    {
                        "id": "skeleton-codex-r1",
                        "kind": "review_round",
                        "family": "codex",
                        "raw_path": ".orchestrator/raw/skeleton-codex-r1.txt",
                        "result": {
                            "findings": [
                                {
                                    "id": "F1",
                                    "severity": "P3",
                                    "summary": "skeleton lacked non-goals",
                                }
                            ]
                        },
                    },
                    {
                        "id": "skeleton-codex-r2",
                        "kind": "fix_findings",
                        "family": "codex",
                        "source_round_id": "skeleton-codex-r1",
                        "raw_path": ".orchestrator/raw/skeleton-fix1.txt",
                        "result": {
                            "findings": [
                                {
                                    "id": "F1",
                                    "severity": "P3",
                                    "summary": "skeleton lacked non-goals",
                                    "disposition": "fixed",
                                    "consultation": None,
                                }
                            ]
                        },
                    },
                    {
                        "id": "skeleton-codex-r3",
                        "kind": "delta_review",
                        "family": "codex",
                        "raw_path": ".orchestrator/raw/skeleton-delta1.txt",
                        "result": {"findings": []},
                    },
                    {
                        "id": "skeleton-claude-r1",
                        "kind": "review_round",
                        "family": "claude",
                        "raw_path": ".orchestrator/raw/skeleton-claude-r1.txt",
                        "result": {
                            "findings": [
                                {
                                    "id": "F1",
                                    "severity": "P3",
                                    "summary": "goal wording is ambiguous "
                                    "about float support",
                                }
                            ]
                        },
                    },
                    {
                        "id": "skeleton-codex-r4",
                        "kind": "fix_findings",
                        "family": "codex",
                        "source_round_id": "skeleton-claude-r1",
                        "raw_path": ".orchestrator/raw/skeleton-fix2.txt",
                        "result": {
                            "findings": [
                                {
                                    "id": "F1",
                                    "severity": "P3",
                                    "summary": "goal wording is ambiguous "
                                    "about float support",
                                    "disposition": "rejected",
                                    "consultation": {
                                        "resolution": ADJ_RATIONALE,
                                    },
                                    "prevention": {
                                        "documented_in": "docs/skeleton.md",
                                        "note": "explicit float-support "
                                        "note added",
                                    },
                                }
                            ]
                        },
                    },
                    {
                        "id": "skeleton-claude-r2",
                        "kind": "review_round",
                        "family": "claude",
                        "raw_path": ".orchestrator/raw/skeleton-claude-r2.txt",
                        "result": {"findings": []},
                    },
                ],
                "seals": [
                    {
                        "attempt": 1,
                        "passed": True,
                        "invalidated": None,
                        "halves": {
                            "codex": _clean_half(
                                ".orchestrator/raw/skeleton-seal-a1-codex.txt"
                            ),
                            "claude": _clean_half(
                                ".orchestrator/raw/skeleton-seal-a1-claude.txt"
                            ),
                        },
                    }
                ],
                "gate_commit": "abc1234",
                "closed_record": None,
            },
            {
                "kind": "slice_doc",
                "slice_id": 1,
                "status": "sealed",
                "artifact": "docs/slice-01.md",
                "draft": None,
                "rounds": [],
                "seals": [],
                "gate_commit": None,
                "closed_record": None,
            },
            {
                "kind": "slice_impl",
                "slice_id": 1,
                "status": "sealed",
                "artifact": None,
                "draft": {
                    "kind": "implement",
                    "raw_path": ".orchestrator/raw/slice_impl-01-draft.txt",
                },
                "rounds": [
                    {
                        "id": "slice_impl-01-codex-r1",
                        "kind": "fix_findings",
                        "family": "codex",
                        "source_round_id": "slice_impl-01-verify-pre_review-1",
                        "raw_path": ".orchestrator/raw/slice_impl-01-fix1.txt",
                        "result": {
                            "findings": [
                                {
                                    "id": "V1",
                                    "severity": "P1",
                                    "summary": "div() multiplied",
                                    "disposition": "fixed",
                                    "consultation": None,
                                }
                            ]
                        },
                    },
                    {
                        "id": "slice_impl-01-codex-r2",
                        "kind": "delta_review",
                        "family": "codex",
                        "raw_path": ".orchestrator/raw/slice_impl-01-delta1.txt",
                        "result": {"findings": []},
                    },
                    {
                        "id": "slice_impl-01-claude-r1",
                        "kind": "review_round",
                        "family": "claude",
                        "raw_path": ".orchestrator/raw/slice_impl-01-claude-r1.txt",
                        "result": {"findings": []},
                    },
                ],
                "seals": [
                    {
                        "attempt": 1,
                        "passed": False,
                        "invalidated": "seal half codex modified the "
                        "workspace; its output is invalid",
                        "halves": {
                            "codex": {
                                "result": {"findings": []},
                                "raw_path": ".orchestrator/raw/"
                                "slice_impl-01-seal-a1-codex.txt",
                                "duration_s": 1.0,
                                "workspace_modified": True,
                            },
                            "claude": _clean_half(
                                ".orchestrator/raw/slice_impl-01-seal-a1-claude.txt"
                            ),
                        },
                    },
                    {
                        "attempt": 2,
                        "passed": False,
                        "invalidated": None,
                        "halves": {
                            "codex": _clean_half(
                                ".orchestrator/raw/slice_impl-01-seal-a2-codex.txt"
                            ),
                            "claude": {
                                "result": {
                                    "findings": [
                                        {
                                            "id": "S1",
                                            "severity": "P3",
                                            "summary": "workspace lacks a README",
                                        }
                                    ]
                                },
                                "raw_path": ".orchestrator/raw/"
                                "slice_impl-01-seal-a2-claude.txt",
                                "duration_s": 1.0,
                                "workspace_modified": False,
                            },
                        },
                    },
                    {
                        "attempt": 3,
                        "passed": True,
                        "invalidated": None,
                        "halves": {
                            "codex": _clean_half(
                                ".orchestrator/raw/slice_impl-01-seal-a3-codex.txt"
                            ),
                            "claude": _clean_half(
                                ".orchestrator/raw/slice_impl-01-seal-a3-claude.txt"
                            ),
                        },
                    },
                ],
                "gate_commit": None,
                "closed_record": {
                    "at": "2026-01-02T03:04:05+0000",
                    "slice_id": 1,
                    "rounds": 3,
                    "seal_attempts": 3,
                },
            },
        ],
    }


class TestRenderMilestone(unittest.TestCase):
    def setUp(self):
        self.state = make_state()
        self.text = ledgers.render_milestone(self.state)

    def test_generated_marker_leads_the_file(self):
        self.assertTrue(self.text.startswith(GENERATED_MARKER))
        self.assertIn("do not edit", self.text)

    def test_status_goal_and_slice_table(self):
        self.assertIn("# Milestone", self.text)
        self.assertIn("Status: **closed**", self.text)
        self.assertIn("Ship a tiny calculator with tests", self.text)
        self.assertIn("| 01 | Calculator core |", self.text)

    def test_unit_rows_with_seal_summaries_and_gate_commit(self):
        self.assertIn("| skeleton | sealed | 6 | a1:pass | abc1234 |", self.text)
        self.assertIn(
            "| slice_doc-01 (Calculator core) | sealed | 0 | - | - |", self.text
        )
        # The invalidated attempt renders as "invalid", the findings attempt
        # as "findings", the clean one as "pass"; no gate commit -> "-".
        self.assertIn(
            "| slice_impl-01 (Calculator core) | sealed | 3 "
            "| a1:invalid, a2:findings, a3:pass | - |",
            self.text,
        )

    def test_no_failure_section_without_failure(self):
        self.assertNotIn("## Failure", self.text)

    def test_failure_section_rendered_when_failed(self):
        state = make_state()
        state["milestone"]["status"] = "failed"
        state["failure"] = {
            "at": "2026-01-03T00:00:00+0000",
            "unit": "slice_impl-01",
            "reason": "boom",
        }
        text = ledgers.render_milestone(state)
        self.assertIn("Status: **failed**", text)
        self.assertIn("## Failure", text)
        self.assertIn("- at: 2026-01-03T00:00:00+0000", text)
        self.assertIn("- unit: slice_impl-01", text)
        self.assertIn("- reason: boom", text)


class TestRenderReviewLog(unittest.TestCase):
    def setUp(self):
        self.state = make_state()
        self.text = ledgers.render_review_log(self.state)

    def test_generated_marker_and_heading(self):
        self.assertTrue(self.text.startswith(GENERATED_MARKER))
        self.assertIn("# Review Log", self.text)

    def test_unit_sections_present(self):
        self.assertIn("## skeleton", self.text)
        self.assertIn("## slice_doc-01 (Calculator core)", self.text)
        self.assertIn("## slice_impl-01 (Calculator core)", self.text)

    def test_draft_line(self):
        self.assertIn(
            "- draft: kind `draft_skeleton`, artifact `docs/skeleton.md` "
            "(raw: `.orchestrator/raw/skeleton-draft.txt`)",
            self.text,
        )

    def test_reported_review_round_row(self):
        # Reviewer findings carry no disposition: they count as "reported".
        self.assertIn(
            "| skeleton-codex-r1 | review_round | codex | 1 "
            "| 1 reported "
            "| `.orchestrator/raw/skeleton-codex-r1.txt` |",
            self.text,
        )

    def test_fix_round_rows_with_triage_and_consultation(self):
        self.assertIn(
            "| skeleton-codex-r2 | fix_findings | codex | 1 "
            "| 1 fixed "
            "| `.orchestrator/raw/skeleton-fix1.txt` |",
            self.text,
        )
        # The rejection carries its consultation.
        self.assertIn(
            "| skeleton-codex-r4 | fix_findings | codex | 1 "
            "| 1 rejected (1 consulted) "
            "| `.orchestrator/raw/skeleton-fix2.txt` |",
            self.text,
        )

    def test_clean_delta_review_row(self):
        self.assertIn(
            "| skeleton-codex-r3 | delta_review | codex | 0 | clean "
            "| `.orchestrator/raw/skeleton-delta1.txt` |",
            self.text,
        )

    def test_seal_attempt_headings_cover_all_outcomes(self):
        self.assertIn("### Seal attempt a1 — PASSED", self.text)  # skeleton
        self.assertIn("### Seal attempt a1 — INVALIDATED", self.text)
        self.assertIn("### Seal attempt a2 — findings", self.text)
        self.assertIn("### Seal attempt a3 — PASSED", self.text)

    def test_invalidated_attempt_details(self):
        self.assertIn(
            "- invalidated: seal half codex modified the workspace; "
            "its output is invalid",
            self.text,
        )
        self.assertIn(
            "- codex half: 0 finding(s); workspace_modified=True; "
            "raw `.orchestrator/raw/slice_impl-01-seal-a1-codex.txt`",
            self.text,
        )

    def test_findings_attempt_lists_each_finding(self):
        self.assertIn(
            "- claude half: 1 finding(s); workspace_modified=False; "
            "raw `.orchestrator/raw/slice_impl-01-seal-a2-claude.txt`",
            self.text,
        )
        self.assertIn("  - [P3] workspace lacks a README", self.text)

    def test_requeued_implementation_debt_is_not_republished(self):
        state = make_state()
        state["events"] = []
        impl = state["units"][2]
        impl["status"] = st.U_SEALING
        impl["debt"] = [{
            "id": "claude-F9",
            "severity": "P3",
            "summary": "historical implementation defect",
            "raised_by": "claude",
            "cleared_by": "codex",
            "reason": "previously deferred",
        }]

        st.requeue_implementation_debt(state)
        text = ledgers.render_review_log(state)

        self.assertEqual(len(impl["debt"]), 1)
        self.assertNotIn("historical implementation defect", text)
        self.assertNotIn("Deferred debt", text)


class TestRenderAdjudications(unittest.TestCase):
    def setUp(self):
        self.state = make_state()
        self.text = ledgers.render_adjudications(self.state)

    def test_generated_marker_and_heading(self):
        self.assertTrue(self.text.startswith(GENERATED_MARKER))
        self.assertIn("# Adjudicated Rejections", self.text)

    def test_entry_derived_from_the_rejected_fix_finding(self):
        # Entry id = "<source_round_id>/<finding_id>" — the review round
        # whose finding the fixer rejected, not the fix round's own id.
        self.assertIn("## [%s]" % ADJ_ID, self.text)
        self.assertIn("- unit: skeleton", self.text)
        self.assertIn("- severity: P3", self.text)
        self.assertIn(
            "- finding: goal wording is ambiguous about float support",
            self.text,
        )

    def test_rationale_comes_from_the_consultation_resolution(self):
        self.assertIn("- rationale: %s" % ADJ_RATIONALE, self.text)

    def test_prevention_line_rendered_when_present(self):
        self.assertIn(
            "- prevention: docs/skeleton.md (explicit float-support note "
            "added)",
            self.text,
        )

    def test_fixed_and_verification_findings_are_not_adjudications(self):
        # Only "rejected" dispositions enter the registry: the fixed F1 and
        # the fixed V1 must not appear.
        self.assertNotIn("skeleton-codex-r1/F1", self.text)
        self.assertNotIn("slice_impl-01-verify-pre_review-1/V1", self.text)
        self.assertEqual(self.text.count("## ["), 1)

    def test_no_prevention_line_when_absent(self):
        state = make_state()
        rejected = state["units"][0]["rounds"][4]["result"]["findings"][0]
        rejected["prevention"] = None
        text = ledgers.render_adjudications(state)
        self.assertIn("## [%s]" % ADJ_ID, text)
        self.assertNotIn("- prevention:", text)

    def test_missing_rationale_renders_placeholder(self):
        state = make_state()
        rejected = state["units"][0]["rounds"][4]["result"]["findings"][0]
        rejected["consultation"] = None
        text = ledgers.render_adjudications(state)
        self.assertIn("- rationale: (none)", text)

    def test_empty_case(self):
        state = make_state()
        # Strip the rejection: no adjudicated entries remain.
        state["units"][0]["rounds"] = state["units"][0]["rounds"][:4]
        text = ledgers.render_adjudications(state)
        self.assertTrue(text.startswith(GENERATED_MARKER))
        self.assertIn("# Adjudicated Rejections", text)
        self.assertIn("(none)", text)
        self.assertNotIn("## [", text)
        self.assertNotIn("Settled findings", text)


class TestRenderClosure(unittest.TestCase):
    def setUp(self):
        self.state = make_state()
        self.impl = self.state["units"][2]

    def test_closure_content(self):
        text = ledgers.render_closure(self.state, self.impl)
        self.assertTrue(text.startswith(GENERATED_MARKER))
        self.assertIn("# Closure — slice 01 (Calculator core)", text)
        self.assertIn("- closed at: 2026-01-02T03:04:05+0000", text)
        self.assertIn("- rounds: 3", text)
        self.assertIn("- seal attempts: 3", text)
        self.assertIn("- review state: review_clean", text)

    def test_gate_commit_placeholder_when_committed_with_closure(self):
        # The closure ledger is generated BEFORE its own gate commit, so a
        # unit without a recorded sha points at the commit that carries it.
        text = ledgers.render_closure(self.state, self.impl)
        self.assertIn("- gate commit: (this commit)", text)

    def test_gate_commit_sha_when_recorded(self):
        state = copy.deepcopy(self.state)
        state["units"][2]["gate_commit"] = "fff9999"
        text = ledgers.render_closure(state, state["units"][2])
        self.assertIn("- gate commit: fff9999", text)


class TestGenerate(unittest.TestCase):
    def setUp(self):
        self.state = make_state()
        self.tmp = tempfile.TemporaryDirectory(prefix="orch-ledgers-")
        self.addCleanup(self.tmp.cleanup)
        self.ws = self.tmp.name

    def _read_all(self, rels):
        blobs = {}
        for rel in rels:
            with open(os.path.join(self.ws, rel), "rb") as fh:
                blobs[rel] = fh.read()
        return blobs

    def test_returns_relative_paths_under_docs(self):
        rels = ledgers.generate(self.state, self.ws)
        self.assertEqual(
            rels,
            [
                os.path.join("docs", "MILESTONE.md"),
                os.path.join("docs", "review-log.md"),
                os.path.join("docs", "adjudications.md"),
                os.path.join("docs", "closures", "slice-01.md"),
            ],
        )
        for rel in rels:
            self.assertFalse(os.path.isabs(rel), rel)
            self.assertTrue(os.path.isfile(os.path.join(self.ws, rel)), rel)

    def test_written_files_match_render_functions(self):
        rels = ledgers.generate(self.state, self.ws)
        blobs = self._read_all(rels)
        self.assertEqual(
            blobs[os.path.join("docs", "MILESTONE.md")].decode("utf-8"),
            ledgers.render_milestone(self.state),
        )
        self.assertEqual(
            blobs[os.path.join("docs", "review-log.md")].decode("utf-8"),
            ledgers.render_review_log(self.state),
        )
        self.assertEqual(
            blobs[os.path.join("docs", "adjudications.md")].decode("utf-8"),
            ledgers.render_adjudications(self.state),
        )
        self.assertEqual(
            blobs[os.path.join("docs", "closures", "slice-01.md")].decode("utf-8"),
            ledgers.render_closure(self.state, self.state["units"][2]),
        )

    def test_adjudications_file_carries_the_registry_entry(self):
        ledgers.generate(self.state, self.ws)
        with open(
            os.path.join(self.ws, "docs", "adjudications.md"), encoding="utf-8"
        ) as fh:
            text = fh.read()
        self.assertIn("## [%s]" % ADJ_ID, text)
        self.assertIn(ADJ_RATIONALE, text)

    def test_generated_marker_in_every_file(self):
        rels = ledgers.generate(self.state, self.ws)
        for rel, blob in self._read_all(rels).items():
            self.assertIn(GENERATED_MARKER.encode("utf-8"), blob, rel)

    def test_deterministic_two_calls_identical_bytes(self):
        rels1 = ledgers.generate(self.state, self.ws)
        first = self._read_all(rels1)
        rels2 = ledgers.generate(self.state, self.ws)
        second = self._read_all(rels2)
        self.assertEqual(rels1, rels2)
        self.assertEqual(first, second)

    def test_closure_only_for_closed_slice_impl(self):
        # Not for slice_doc units, and not for a slice_impl that has no
        # closed_record yet.
        self.state["units"][2]["closed_record"] = None
        rels = ledgers.generate(self.state, self.ws)
        self.assertEqual(
            rels,
            [
                os.path.join("docs", "MILESTONE.md"),
                os.path.join("docs", "review-log.md"),
                os.path.join("docs", "adjudications.md"),
            ],
        )
        self.assertFalse(
            os.path.exists(os.path.join(self.ws, "docs", "closures"))
        )


class TestCanonicalLayout(unittest.TestCase):
    """docs_dir-driven layout: legacy "docs" keeps the flat MILESTONE.md
    shape; anything else uses the canonical milestone layout and
    maintains the parent milestone index."""

    def make_state(self, docs_dir=None, name=None):
        cfg = {"families_order": ["codex", "claude"]}
        if docs_dir:
            cfg["docs_dir"] = docs_dir
        return st.new_state("goal", "/ws", cfg, name=name)

    def test_legacy_paths(self):
        state = self.make_state()
        self.assertTrue(ledgers.is_legacy(state))
        self.assertEqual(ledgers.record_path(state), "docs/MILESTONE.md")
        self.assertEqual(ledgers.skeleton_path(state), "docs/skeleton.md")
        self.assertEqual(ledgers.slice_note_path(state, 3),
                         "docs/slice-03.md")
        self.assertIsNone(ledgers.index_path(state))

    def test_canonical_paths(self):
        state = self.make_state("implementation/milestones/{slug}",
                                name="Chat Tombstone Delete")
        d = "implementation/milestones/chat-tombstone-delete"
        self.assertFalse(ledgers.is_legacy(state))
        self.assertEqual(ledgers.docs_dir(state), d)
        self.assertEqual(ledgers.record_path(state), d + "/README.md")
        self.assertEqual(ledgers.skeleton_path(state), d + "/skeleton.md")
        self.assertEqual(ledgers.slice_note_path(state, 2),
                         d + "/slices/slice-02.md")
        self.assertEqual(ledgers.index_path(state),
                         "implementation/milestones/README.md")

    def test_index_upsert_preserves_hand_written_content(self):
        state = self.make_state("implementation/milestones/{slug}",
                                name="m one")
        first = ledgers.render_index_update(state, None)
        self.assertIn("# Milestone Index", first)
        self.assertIn(ledgers.INDEX_START, first)
        self.assertIn("| [m one](m-one/) | open |", first)
        # Hand-written prose around the block survives an update.
        hand = "Intro prose.\n\n" + first + "\nOutro prose.\n"
        state["milestone"]["status"] = "closed"
        st.append_event(state, "gate_commit", sha="abc")
        updated = ledgers.render_index_update(state, hand)
        self.assertIn("Intro prose.", updated)
        self.assertIn("Outro prose.", updated)
        self.assertIn("| closed |", updated)
        self.assertEqual(updated.count("| [m one](m-one/)"), 1)

    def test_index_upsert_keeps_other_milestones(self):
        a = self.make_state("implementation/milestones/{slug}", name="aaa")
        b = self.make_state("implementation/milestones/{slug}", name="bbb")
        text = ledgers.render_index_update(a, None)
        text = ledgers.render_index_update(b, text)
        self.assertIn("[aaa](aaa/)", text)
        self.assertIn("[bbb](bbb/)", text)

    def test_generate_canonical_writes_layout_and_index(self):
        state = self.make_state("implementation/milestones/{slug}",
                                name="demo run")
        with tempfile.TemporaryDirectory() as ws:
            written = ledgers.generate(state, ws)
            d = "implementation/milestones/demo-run"
            self.assertIn(d + "/README.md", written)
            self.assertIn("implementation/milestones/README.md", written)
            self.assertTrue(os.path.exists(
                os.path.join(ws, d, "README.md")))
            idx = open(os.path.join(
                ws, "implementation/milestones/README.md"),
                encoding="utf-8").read()
            self.assertIn("[demo run](demo-run/)", idx)


class TestIndexHardening(unittest.TestCase):
    def make_state(self, name):
        return st.new_state(
            "goal", "/ws",
            {"families_order": ["codex", "claude"],
             "docs_dir": "implementation/milestones/{slug}"},
            name=name,
        )

    def test_malformed_markers_raise_instead_of_eating_prose(self):
        state = self.make_state("m")
        hostile = ledgers.INDEX_END + "\nprose\n" + ledgers.INDEX_START
        with self.assertRaises(ledgers.LedgerError):
            ledgers.render_index_update(state, hostile)
        orphan = ledgers.INDEX_START + "\nprose after orphan start\n"
        with self.assertRaises(ledgers.LedgerError):
            ledgers.render_index_update(state, orphan)

    def test_pipe_in_name_neither_corrupts_nor_collides(self):
        a = self.make_state("api | phase 1")
        b = self.make_state("api | phase 2")
        text = ledgers.render_index_update(a, None)
        text = ledgers.render_index_update(b, text)
        self.assertIn("(api-phase-1/)", text)
        self.assertIn("(api-phase-2/)", text)
        # sanitized labels: no raw pipe inside the link text
        self.assertNotIn("[api | phase", text)

    def test_non_utf8_index_raises_ledger_error(self):
        state = self.make_state("m")
        with tempfile.TemporaryDirectory() as ws:
            idx_dir = os.path.join(ws, "implementation", "milestones")
            os.makedirs(idx_dir)
            with open(os.path.join(idx_dir, "README.md"), "wb") as fh:
                fh.write(b"# Index\n\xff\xfe broken\n")
            with self.assertRaises(ledgers.LedgerError):
                ledgers.generate(state, ws)


class TestSlugify(unittest.TestCase):
    def test_basic(self):
        self.assertEqual(st.slugify("LPC - N30"), "lpc-n30")
        # Unicode letters are legitimate directory characters.
        self.assertEqual(st.slugify("  Ñandú  ??? "), "ñandú")
        self.assertEqual(st.slugify(""), "milestone")
        self.assertEqual(st.slugify(None), "milestone")
        self.assertLessEqual(len(st.slugify("x" * 200)), 60)


if __name__ == "__main__":
    unittest.main()
